### Dynamic DB Connect
POST http://localhost:8080/api/db/connect
Content-Type: multipart/form-data

databaseName=reporting&username=demo&password=secret

### Dynamic DB Close
POST http://localhost:8080/api/db/close
Content-Type: multipart/form-data

connectionId=UUID_FROM_CONNECT

### Dynamic App Users
POST http://localhost:8080/api/db/users
Content-Type: application/json

{
  "connectionId": "UUID_FROM_CONNECT",
  "username": "alice",
  "isAdmin": true,
  "limit": 10
}

### Dynamic Customers
POST http://localhost:8080/api/db/customers
Content-Type: application/json

{
  "connectionId": "UUID_FROM_CONNECT",
  "email": "alice@example.com",
  "fullName": "Alice",
  "country": "TW",
  "city": "Taipei",
  "isVip": true,
  "signupAfter": "2025-01-01T00:00:00+08:00",
  "signupBefore": "2025-12-31T23:59:59+08:00",
  "limit": 50
}

### Dynamic Categories
POST http://localhost:8080/api/db/categories
Content-Type: application/json

{
  "connectionId": "UUID_FROM_CONNECT",
  "categoryName": "3C",
  "limit": 50
}

### Dynamic Products
POST http://localhost:8080/api/db/products
Content-Type: application/json

{
  "connectionId": "UUID_FROM_CONNECT",
  "sku": "SKU-001",
  "productName": "Phone",
  "categoryId": 1,
  "isActive": true,
  "minListPrice": 1000,
  "maxListPrice": 20000,
  "limit": 50
}

### Dynamic Inventory Movements
POST http://localhost:8080/api/db/inventory-movements
Content-Type: application/json

{
  "connectionId": "UUID_FROM_CONNECT",
  "productId": 10,
  "movementType": "IN",
  "warehouse": "TW-TP",
  "movedAfter": "2025-01-01T00:00:00+08:00",
  "movedBefore": "2025-12-31T23:59:59+08:00",
  "limit": 100
}

### Dynamic Orders
POST http://localhost:8080/api/db/orders
Content-Type: application/json

{
  "connectionId": "UUID_FROM_CONNECT",
  "customerId": 100,
  "orderStatus": "PAID",
  "orderChannel": "WEB",
  "createdAfter": "2025-01-01T00:00:00+08:00",
  "createdBefore": "2025-12-31T23:59:59+08:00",
  "limit": 50
}

### Dynamic Order Items
POST http://localhost:8080/api/db/order-items
Content-Type: application/json

{
  "connectionId": "UUID_FROM_CONNECT",
  "orderId": 5001,
  "productId": 20,
  "limit": 100
}

### Dynamic Payments
POST http://localhost:8080/api/db/payments
Content-Type: application/json

{
  "connectionId": "UUID_FROM_CONNECT",
  "orderId": 5001,
  "paymentMethod": "CREDIT_CARD",
  "paymentStatus": "SUCCESS",
  "paidAfter": "2025-01-01T00:00:00+08:00",
  "paidBefore": "2025-12-31T23:59:59+08:00",
  "limit": 50
}

### Dynamic Returns
POST http://localhost:8080/api/db/returns
Content-Type: application/json

{
  "connectionId": "UUID_FROM_CONNECT",
  "orderId": 5001,
  "productId": 20,
  "returnStatus": "APPROVED",
  "requestedAfter": "2025-01-01T00:00:00+08:00",
  "requestedBefore": "2025-12-31T23:59:59+08:00",
  "limit": 50
}
